### ISSUE TITLE
Syntax error/build broken in versions 0.3.7 and newer

### ISSUE THREAD

**Issue by craigotis** [ember-cli/ember-cli-htmlbars-inline-precompile#84]
This commit:

https://github.com/ember-cli/ember-cli-htmlbars-inline-precompile/commit/d82e88aea19e619a951768cad825d3e742288e0e

Seems to have broken the `0.3.7` build and onward, in certain circumstances. We have a legacy project that was building properly until the 0.3.7 release, at which point it began failing with:
```
[ERROR] /home/craig/projects/myproject/node_modules/ember-cli-htmlbars-inline-precompile/index.js:15
[ERROR]   init() {
[ERROR]       ^
[ERROR] Unexpected token (
[ERROR] /home/craig/projects/myproject/node_modules/ember-cli-htmlbars-inline-precompile/index.js:15
[ERROR]   init() {
[ERROR]       ^
[ERROR] SyntaxError: Unexpected token (
[ERROR]     at exports.runInThisContext (vm.js:73:16)
[ERROR]     at Module._compile (module.js:443:25)
[ERROR]     at Object.Module._extensions..js (module.js:478:10)
[ERROR]     at Module.load (module.js:355:32)
[ERROR]     at Function.Module._load (module.js:310:12)
[ERROR]     at Module.require (module.js:365:17)
[ERROR]     at require (module.js:384:17)
[ERROR]     at Function.Addon.lookup (/home/craig/projects/myproject/node_modules/ember-cli/lib/models/addon.js:725:19)
[ERROR]     at /home/craig/projects/myproject/node_modules/ember-cli/lib/models/addons-factory.js:47:36
[ERROR]     at visit (/home/craig/projects/myproject/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
```
We're using:
```
"devDependencies": {
    ...
    "ember-cli-htmlbars-inline-precompile": "~0.3.0",
    ...
}
```
Which when pulling in anything newer than 0.3.6, fails. If I hard-code `"0.3.6"`, we build fine. Build with `"0.3.7"` and we fail.

Please see our full dependency list below for any obvious issues, but it seems like this kind of change (and dependence on newer syntax) should be reserved for a minor version bump.

```
"devDependencies": {
    "bower": "~1.3.12",
    "broccoli-asset-rev": "~2.2.0",
    "ember-cli": "~1.13.13",
    "ember-cli-app-version": "~1.0.0",
    "ember-cli-babel": "~5.1.5",
    "ember-cli-dependency-checker": "~1.1.0",
    "ember-cli-htmlbars": "~1.0.1",
    "ember-cli-htmlbars-inline-precompile": "0.3.6",
    "ember-cli-ic-ajax": "~0.2.4",
    "ember-cli-inject-live-reload": "~1.3.1",
    "ember-cli-qunit": "~1.0.4",
    "ember-cli-release": "~0.2.8",
    "ember-cli-sri": "~1.2.0",
    "ember-cli-uglify": "~1.2.0",
    "ember-data": "~1.13.15",
    "ember-disable-proxy-controllers": "~1.0.1",
    "ember-export-application-global": "~1.0.4",
    "phantomjs": "~1.9.19"
  }
```

**Comment by rwjblue** [comment]
Seems like an error due to usage of concise function syntax (i.e. `init() {}` instead of `init: function() {}`), which is likely because you are using Node 0.10 or Node 0.12.

I'm happy to merge and release a fix for 0.3.x if you would like to target a PR against the `v-0-3-x` branch.

**Comment by craigotis** [comment]
Thanks @rwjblue, I opened #85.

**Comment by btecu** [comment]
This can be closed.

**Comment by rwjblue** [comment]
Thanks @btecu
