### ISSUE TITLE
Unable to build ember after updating to 0.4.1 or higher

### ISSUE THREAD

**Issue by bryanhickerson** [ember-cli/ember-cli-htmlbars-inline-precompile#86]
I updated ember-cli-htmlbars-inline-precompile when updating to ember-cli 2.13.2 and found I could no longer build ember. I pinpointed it to the 0.4.1 version of this package. Any suggestions on how to diagnose this issue?
```
Build failed.
The Broccoli Plugin: [BroccoliMergeTrees] failed with:
Error: Build Canceled: Broccoli Builder ran into an error with Babel plugin. 💥
    at new BroccoliBuildError (/Users/bryan/src/betterup-app/frontend/node_modules/broccoli-builder/lib/broccoli-build-error.js:40:9)
    at /Users/bryan/src/betterup-app/frontend/node_modules/broccoli-builder/lib/builder.js:168:19
    at tryCatch (/Users/bryan/src/betterup-app/frontend/node_modules/rsvp/dist/rsvp.js:539:12)
    at invokeCallback (/Users/bryan/src/betterup-app/frontend/node_modules/rsvp/dist/rsvp.js:554:13)
    at publish (/Users/bryan/src/betterup-app/frontend/node_modules/rsvp/dist/rsvp.js:522:7)
    at publishRejection (/Users/bryan/src/betterup-app/frontend/node_modules/rsvp/dist/rsvp.js:457:3)
    at flush (/Users/bryan/src/betterup-app/frontend/node_modules/rsvp/dist/rsvp.js:2414:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/bryan/src/betterup-app/frontend/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/bryan/src/betterup-app/frontend/node_modules/broccoli-merge-trees/index.js:42:10)
    at Class.postprocessTree (/Users/bryan/src/betterup-app/frontend/node_modules/ember-browserify/lib/index.js:79:14)
    at projectOrAddon.addons.reduce (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
    at Array.reduce (native)
    at addonProcessTree (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
    at EmberApp.addonPostprocessTree (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:586:12)
    at EmberApp.appAndDependencies (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1114:33)
    at EmberApp.javascript (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1225:30)
    at EmberApp.toArray (/Users/bryan/src/betterup-app/frontend/node_modules/ember-cli/lib/broccoli/ember-app.js:1662:12)
```

**Comment by bryanhickerson** [comment]
Updated some dependencies/deprecations and I don't hit this anymore (There was a fair amount of activity since I tried this activity, so it's unclear which actually eliminated the issue). Actually hitting #71 instead, will follow the suggestions there.
